name: Test on Windows

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup Go 1.x
      uses: actions/setup-go@v2

    - name: Test
      run: go test -v ./cpplan
